# Generated by Django 2.0.5 on 2018-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('hire_date', models.DateTimeField(verbose_name='Hire Date')),
            ],
        ),
    ]
